version: '3.3'

services:
   db:
     platform: linux/x86_64 # M1 Mac対応
     container_name: "mysql__yyyymmdd"
     image: mysql:5.7
     ports:
       - "3307:3306" #0～65535:3306（default:「3307:3306」）
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress # DB名
       MYSQL_USER: wordpress # DBユーザー名
       MYSQL_PASSWORD: wordpress # DBパスワード

   wordpress:
     container_name: "wp__yyyymmdd"
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80" #0～65535:80（default:「8000:80」）
     volumes:
       - ./public:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress # DB名
       WORDPRESS_DB_USER: wordpress # DBユーザー名
       WORDPRESS_DB_PASSWORD: wordpress # DBパスワード
volumes:
    db_data:
        driver: local
